<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\CaseReport;
use App\Models\CaseReportItem;
use App\Models\Invoice;
use App\Models\InvoiceItem;
use App\Models\Payment;
use App\Models\Patient;
use App\Models\Referer;
use App\Models\ScanType;
use App\Models\Scan;
use App\Models\PaymentMethod;
use App\Models\User;
use App\Models\Branch;
use Carbon\Carbon;
use Illuminate\Support\Str;

class CaseReportSystemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ini_set('memory_limit', '512M');

        // 1. Fetch Master Data
        $patients = Patient::all();
        $referers = Referer::all();
        $scanTypes = ScanType::with('scans')->get();
        $paymentMethods = PaymentMethod::all();
        $users = User::all();
        $branches = Branch::all();

        if ($patients->isEmpty() || $referers->isEmpty() || $scanTypes->isEmpty() || $paymentMethods->isEmpty() || $branches->isEmpty() || $users->isEmpty()) {
            $this->command->error('Missing required master data (Patients, Referers, Scan Types, Payment Methods, Users, Branches). Please run foundational seeders first.');
            return;
        }

        // Configuration
        $totalCasesToGenerate = 100;

        // Sequence Generators (Auto-IDs)
        $nextCaseIdFormat = $this->getNextSequenceId(CaseReport::class, 'case_id', 'CAS');
        $nextInvoiceIdFormat = $this->getNextSequenceId(Invoice::class, 'invoice_id', 'INV');
        $nextPaymentIdFormat = $this->getNextSequenceId(Payment::class, 'payment_id', 'PAY');

        // Item Reference tracking by Prefix
        $itemReferenceTracker = [];

        // Track Scan Types ensuring each hits minimum 5 instances
        $scanTypeUsage = [];
        foreach ($scanTypes as $st) {
            $scanTypeUsage[$st->id] = 0;
        }

        // Track Referer limits (Minimum 5 per referer)
        // We have 'N' referers. We need to distribute $totalCasesToGenerate cases across them.
        $casesCreatedPerReferer = [];
        foreach ($referers as $ref) {
            $casesCreatedPerReferer[$ref->id] = 0;
        }

        // Generate Case Reports
        $this->command->info("Starting creation of {$totalCasesToGenerate} case reports with items, invoices, and payments...");

        DB::beginTransaction();

        try {
            for ($i = 0; $i < $totalCasesToGenerate; $i++) {
                
                // --- a. Setup Associations & Dates ---
                // Force distribution: cycle through referers ensuring they hit 5 quickly
                $referer = $this->selectReferer($referers, $casesCreatedPerReferer);
                $patient = $patients->random();
                $branch = $branches->random();
                $user = $users->random();

                // Random date within last 90 days. Keep time business hours.
                $daysSub = rand(0, 90);
                $scanningDate = Carbon::now()->subDays($daysSub);
                $checkIn = (clone $scanningDate)->setTime(rand(9, 16), rand(0, 59));
                $checkOut = (clone $checkIn)->addMinutes(rand(15, 120));

                $caseId = 'CAS' . str_pad($nextCaseIdFormat['next_num']++, 4, '0', STR_PAD_LEFT);

                // --- b. Insert Case Report ---
                $caseReport = CaseReport::create([
                    'case_id' => $caseId,
                    'patient_fk_id' => $patient->id,
                    'referer_fk_id' => $referer->id,
                    'description' => 'Seeded Case Report generated by system seeder for testing.',
                    'status' => rand(0, 100) > 80 ? 'available' : 'pending',
                    'expires_at' => null, // Omitted for simplicity
                    'sharing_token' => Str::random(32),
                    'branch_id' => $branch->id,
                    'scanning_date' => $scanningDate->format('Y-m-d'),
                    'check_in' => $checkIn->format('H:i:s'),
                    'check_out' => $checkOut->format('H:i:s'),
                    'is_stat_case' => rand(0, 1) == 1,
                    'added_by' => $user->id,
                    'modified_by' => $user->id,
                    'created_at' => $scanningDate,
                    'updated_at' => $scanningDate
                ]);

                // --- c. Insert Case Report Items ---
                $numItems = rand(1, 3);
                $subTotal = 0;
                $generatedInvoiceItems = [];

                for ($j = 0; $j < $numItems; $j++) {
                    // Pick a scan type (prefer those under 5 initially)
                    $scanType = $this->selectScanType($scanTypes, $scanTypeUsage);
                    $scan = $scanType->scans->isEmpty() ? null : $scanType->scans->random();

                    if (!$scan) continue;

                    $amount = floatval($scan->amount ?? rand(500, 5000));
                    $subTotal += $amount;

                    $caseReportItem = CaseReportItem::create([
                        'case_report_fk_id' => $caseReport->id,
                        'scan_types_fk_id' => $scanType->id,
                        'scan_type_id' => $scanType->id,
                        'scan_details' => [
                            [
                                'scan_id' => $scan->id,
                                'scan_name' => $scan->name,
                                'amount' => $amount
                            ]
                        ],
                        'documents' => [],
                        'remarks' => 'Seeded scan item',
                        'total_amount' => $amount,
                        'created_at' => $scanningDate,
                        'updated_at' => $scanningDate
                    ]);

                    // Prepare for Invoice
                    $generatedInvoiceItems[] = [
                        'case_report_item_fk_id' => $caseReportItem->id,
                        'scan_fk_id' => $scan->id,
                        'description' => "{$scanType->name} - {$scan->name}",
                        'amount' => $amount
                    ];
                }

                if (empty($generatedInvoiceItems)) {
                    continue; // Skip if no valid scans
                }

                // --- d. Insert Invoice ---
                $discount = rand(0, 10) > 7 ? rand(50, 200) : 0; // 30% chance of small discount
                $tax = 0; // Keeping tax simple for seed testing

                $totalAmount = max(0, $subTotal - $discount + $tax);

                $invoiceId = 'INV' . str_pad($nextInvoiceIdFormat['next_num']++, 4, '0', STR_PAD_LEFT);
                $invoiceDate = $scanningDate;

                // Prepare Payment Stats
                $paymentCategoryRandom = rand(1, 100);
                $paidAmount = 0;
                $invoiceStatus = 'unpaid';
                $paymentsToCreate = [];

                if ($paymentCategoryRandom <= 40) {
                    // Fully Paid
                    $paidAmount = $totalAmount;
                    $invoiceStatus = 'fully_paid';
                    $paymentsToCreate[] = $totalAmount;
                } elseif ($paymentCategoryRandom <= 70) {
                    // Partially Paid
                    // Ensure the amount is < total and strictly > 0 if total is non-zero
                    if ($totalAmount > 0) {
                        $partialAmt = rand(10, (int)($totalAmount * 0.8)); // roughly 10% to 80%
                        if ($partialAmt == 0) $partialAmt = 10;
                        $paidAmount = $partialAmt;
                        $invoiceStatus = 'unpaid';
                        $paymentsToCreate[] = $paidAmount;
                    }
                } else {
                    // Unpaid
                    $paidAmount = 0;
                    $invoiceStatus = 'unpaid';
                }

                $invoice = Invoice::create([
                    'invoice_id' => $invoiceId,
                    'case_report_fk_id' => $caseReport->id,
                    'patient_fk_id' => $patient->id,
                    'branch_fk_id' => $branch->id,
                    'discount_fk_id' => null, // Treating as Custom
                    'sub_total' => $subTotal,
                    'discount_amount' => $discount,
                    'tax_amount' => $tax,
                    'total_amount' => $totalAmount,
                    'paid_amount' => $paidAmount,
                    'status' => $invoiceStatus,
                    'invoice_date' => $invoiceDate->format('Y-m-d'),
                    'notes' => 'Seeded invoice.',
                    'added_by' => $user->id,
                    'modified_by' => $user->id,
                    'created_at' => $invoiceDate,
                    'updated_at' => $invoiceDate
                ]);

                // Insert Invoice Items
                foreach ($generatedInvoiceItems as $inItem) {
                    InvoiceItem::create([
                        'invoice_fk_id' => $invoice->id,
                        'case_report_item_fk_id' => $inItem['case_report_item_fk_id'],
                        'scan_fk_id' => $inItem['scan_fk_id'],
                        'description' => $inItem['description'],
                        'amount' => $inItem['amount'],
                        'created_at' => $invoiceDate,
                        'updated_at' => $invoiceDate
                    ]);
                }

                // --- e. Insert Payments (if applicable) ---
                if (!empty($paymentsToCreate)) {
                    foreach ($paymentsToCreate as $payAmount) {
                        $paymentId = 'PAY' . str_pad($nextPaymentIdFormat['next_num']++, 4, '0', STR_PAD_LEFT);

                        // Potentially split the payment across max 2 methods just for UI display richness
                        $splitChance = rand(1, 100);
                        $methodArray = [];

                        if ($splitChance > 80 && $paymentMethods->count() >= 2 && $payAmount > 100) {
                            $m1 = $paymentMethods->random();
                            $m2 = $paymentMethods->where('id', '!=', $m1->id)->random();
                            $split1 = (int)($payAmount / 2);
                            $split2 = $payAmount - $split1;

                            $methodArray = [
                                [
                                    'payment_method_fk_id' => $m1->id,
                                    'method_name' => $m1->name,
                                    'amount' => floatval($split1),
                                    'payment_date' => clone $invoiceDate
                                ],
                                [
                                    'payment_method_fk_id' => $m2->id,
                                    'method_name' => $m2->name,
                                    'amount' => floatval($split2),
                                    'payment_date' => clone $invoiceDate
                                ]
                            ];
                        } else {
                            $m1 = $paymentMethods->random();
                            $methodArray = [
                                [
                                    'payment_method_fk_id' => $m1->id,
                                    'method_name' => $m1->name,
                                    'amount' => floatval($payAmount),
                                    'payment_date' => clone $invoiceDate
                                ]
                            ];
                        }

                        $paymentDetails = [
                            'notes' => 'Seeded payment generated via system script.',
                            'payments' => $methodArray
                        ];

                        Payment::create([
                            'payment_id' => $paymentId,
                            'invoice_fk_id' => $invoice->id,
                            'payment_date' => clone $invoiceDate,
                            'payment_details' => $paymentDetails,
                            'added_by' => $user->id,
                            'modified_by' => $user->id,
                            'created_at' => $invoiceDate,
                            'updated_at' => $invoiceDate
                        ]);
                    }
                }
            }

            DB::commit();
            $this->command->info('Seeding finished perfectly!');

            // Verification Reporting
            $cases = CaseReport::count();
            $items = CaseReportItem::count();
            $invoices = Invoice::count();
            $invItems = InvoiceItem::count();
            $payments = Payment::count();

            $this->command->info("\nVolume Check:");
            $this->command->line("  - Case Reports: $cases");
            $this->command->line("  - Case Report Items: $items");
            $this->command->line("  - Invoices: $invoices");
            $this->command->line("  - Invoice Items: $invItems");
            $this->command->line("  - Payments: $payments");

            $this->command->info("\nDistribution Check:");
            
            $referersUnderLimit = [];
            foreach (Referer::all() as $ref) {
                $count = CaseReport::where('referer_fk_id', $ref->id)->count();
                if ($count < 5) $referersUnderLimit[] = "{$ref->name} ($count)";
            }
            $this->command->line("  - Referers under 5 cases: " . (empty($referersUnderLimit) ? "None (Perfect!)" : implode(", ", $referersUnderLimit)));

            $scanTypesUnderLimit = [];
            foreach (ScanType::all() as $st) {
                $count = InvoiceItem::whereHas('caseReportItem', function($q) use ($st) {
                    $q->where('scan_types_fk_id', $st->id);
                })->count();
                if ($count < 5) $scanTypesUnderLimit[] = "{$st->name} ($count)";
            }
            $this->command->line("  - Scan Types under 5 invoice items: " . (empty($scanTypesUnderLimit) ? "None (Perfect!)" : implode(", ", $scanTypesUnderLimit)));

        } catch (\Exception $e) {
            DB::rollback();
            $this->command->error("Seeding failed: " . $e->getMessage() . " at Line: " . $e->getLine());
        }
    }


    /**
     * Helpers for Sequence & Distribution
     */

    private function getNextSequenceId($modelClass, $column, $prefix)
    {
        $latest = $modelClass::orderBy($column, 'desc')->first();
        if (!$latest) {
            return ['next_num' => 1];
        }

        $lastId = $latest->$column;
        if (preg_match('/' . preg_quote($prefix, '/') . '(\d+)/', $lastId, $matches)) {
            return ['next_num' => intval($matches[1]) + 1];
        }

        return ['next_num' => 1];
    }

    private function selectReferer($referers, &$casesCreatedPerReferer) 
    {
        // Find referers who have < 5
        $underLimitIds = [];
        foreach ($casesCreatedPerReferer as $id => $count) {
            if ($count < 5) {
                $underLimitIds[] = $id;
            }
        }

        if (count($underLimitIds) > 0) {
            // Pick a random under-limit referer
            $pickedId = $underLimitIds[array_rand($underLimitIds)];
            $casesCreatedPerReferer[$pickedId]++;
            return $referers->firstWhere('id', $pickedId);
        }

        // Otherwise pick completely random
        $ref = $referers->random();
        $casesCreatedPerReferer[$ref->id]++;
        return $ref;
    }

    private function selectScanType($scanTypes, &$scanTypeUsage)
    {
        $underLimitIds = [];
        foreach ($scanTypeUsage as $id => $count) {
            if ($count < 5) {
                $underLimitIds[] = $id;
            }
        }

        if (count($underLimitIds) > 0) {
            $pickedId = $underLimitIds[array_rand($underLimitIds)];
            $scanTypeUsage[$pickedId]++;
            return $scanTypes->firstWhere('id', $pickedId);
        }

        $type = $scanTypes->random();
        $scanTypeUsage[$type->id]++;
        return $type;
    }
}
